export type RuleSection = {
  id: string;
  title: string;
  text: string;
  searchTerms?: string[];
};

export const faiRuleSections: RuleSection[] = [
  {
    id: "source-2026",
    title: "Source: FAI Wingsuit Flying Competition Rules 2026",
    text: "Competition Rules Wingsuit Flying, 2026 Edition. Effective 01 March 2026. Ver. 2026.1, 2026-03-01. This search tool is for quick reference only. Competitors and officials should refer to the official FAI document for the authoritative rules.",
    searchTerms: [
      "source",
      "version",
      "2026",
      "official",
      "fai",
      "competition rules",
      "wingsuit flying",
      "wingtip",
      "wingtips",
      "wing tip",
      "wing tips",
    ],
  },

  {
    id: "2.1-general-definitions-wingtip-winglet",
    title: "2.1 General Definitions — Wingtip and Winglet",
    text: "Winglet: An additional vertical element mounted on the wingtip, oriented upward or downward. Wingtip: The outermost structural point or component of a wingsuit’s arm wing, usually rigid, that serves as a terminal boundary of the wing. It may include a handle or reinforced section designed for the pilot to hold or grip during flight to control the shape and tension of the wing.",
    searchTerms: [
      "wingtip",
      "wingtips",
      "wing tip",
      "wing tips",
      "winglet",
      "winglets",
      "arm wing",
      "wing handle",
      "handle",
      "grip",
      "rigid",
      "terminal boundary",
      "outermost structural point",
      "wingsuit arm wing",
    ],
  },

  {
    id: "2.2-competition-window",
    title: "2.2 Competition Window",
    text: "Competition Window: A vertical 1000-meter window, starting at 2500m / 8202ft Geometric Altitude and ending at 1500m / 4921ft Geometric Altitude, in which the performance of the wingsuit flyer is evaluated. The first crossing of the upper window boundary starts the evaluation process, which stops at the first crossing of the lower window boundary.",
    searchTerms: [
      "window",
      "competition window",
      "performance window",
      "scoring window",
      "2500",
      "1500",
      "2500m",
      "1500m",
      "8202",
      "4921",
      "altitude",
      "geometric altitude",
      "upper boundary",
      "lower boundary",
    ],
  },
  {
    id: "2.2-designated-lane",
    title: "2.2 Designated Flight Path and Designated Lane",
    text: "Designated Flight Path: The straight ground track between a point on the competitor’s flight path at the start of the Validation Window and a designated ground reference point. Designated Lane: A lane which is centred on the Designated Flight Path with a width of 600m.",
    searchTerms: [
      "lane",
      "designated lane",
      "flight path",
      "designated flight path",
      "600m",
      "600",
      "ground reference point",
      "reference point",
      "track",
      "line",
    ],
  },
  {
    id: "2.2-validation-window",
    title: "2.2 Validation Window",
    text: "Validation Window: The validation window is the part of the jump which is used to determine the accuracy of the PLD data. The validation window begins 9 seconds after the competitor’s vertical speed first reaches 10m/s and ends 66ft / 20m below the competition window.",
    searchTerms: [
      "validation",
      "validation window",
      "pld accuracy",
      "accuracy",
      "10m/s",
      "9 seconds",
      "20m",
      "66ft",
      "data",
      "gps",
      "position logging device",
    ],
  },
  {
    id: "3.1-pld",
    title: "3.1 Position Logging Device",
    text: "The PLD must record real-time three-dimensional position data with a resolution of at least 5Hz and a position accuracy SEP of less than 10 metres. The PLD must not require action by the competitor to function and must activate recording automatically. Tampering with the device, as determined by the Panel of Judges, will lead to a result of zero for the jump. This decision is not grounds for protest.",
    searchTerms: [
      "pld",
      "gps",
      "position logging device",
      "flysight",
      "logger",
      "data",
      "5hz",
      "accuracy",
      "sep",
      "10 metres",
      "tampering",
      "zero",
      "automatic recording",
      "device",
    ],
  },
  {
    id: "3.2-equipment-general",
    title: "3.2 Equipment — General Requirements",
    text: "All competitors must wear a wingsuit for all competition jumps. All equipment must be inspected by the judge panel to the satisfaction of the Chief Judge prior to use in the competition. Equipment that has not been inspected and approved by the judge panel may not be used on any competition jump. Violation of this rule shall result in a score of zero for the jump.",
    searchTerms: [
      "equipment",
      "inspection",
      "judge panel",
      "chief judge",
      "approved",
      "not inspected",
      "zero",
      "wingsuit",
      "competition jump",
    ],
  },
  {
    id: "3.2-electronics-altitude-warning",
    title: "3.2 Electronics and Audio Altitude Warning Device",
    text: "A competitor shall not wear any other electronic device or wires closer than 2.54cm from the official PLD as measured by the judging staff, except that a second identical PLD unit may be worn without regard to this separation requirement. Each competitor must wear a functioning audio altitude warning device on every jump. Failure to do so will lead to a result of zero for that jump.",
    searchTerms: [
      "electronics",
      "wires",
      "2.54cm",
      "pld",
      "second pld",
      "altitude warning",
      "audible",
      "audio altitude warning",
      "zero",
      "device",
    ],
  },
  {
    id: "5.2-objective",
    title: "5.2 Performance Event Objective",
    text: "The objective is to fly a single wingsuit in three separate tasks to demonstrate a combination of best lift, time task; best glide, distance task; and least drag, speed task. Each round of the event is comprised of the three tasks. Each task is performed on a separate flight.",
    searchTerms: [
      "objective",
      "performance",
      "time",
      "distance",
      "speed",
      "best lift",
      "best glide",
      "least drag",
      "task",
      "round",
    ],
  },
  {
    id: "5.3-tasks",
    title: "5.3 Performance Tasks",
    text: "Time Task: fly with the slowest fall rate possible through the competition window. The result is the time spent in the competition window, expressed in seconds. Distance Task: fly as far as possible through the competition window. The result is the straight-line distance flown over the ground while in the competition window, expressed in metres. Speed Task: fly as fast as possible horizontally over the ground through the competition window. The result is the straight-line distance flown over the ground while in the competition window divided by the time spent in the competition window, expressed in kilometres per hour.",
    searchTerms: [
      "time task",
      "distance task",
      "speed task",
      "slowest fall rate",
      "fall rate",
      "distance",
      "speed",
      "seconds",
      "metres",
      "kilometres per hour",
      "kph",
      "glide",
      "lift",
      "drag",
    ],
  },
  {
    id: "5.4-program-exit-altitude",
    title: "5.4 Program and Exit Altitude",
    text: "A competition shall consist of three rounds, with three tasks in each round, for a total of nine flights. Maximum Exit Altitude: 11,000ft / 3353m, as measured by the approved competition PLD. If the PLD registers an exit higher than the maximum exit altitude, the jump will be considered invalid and a rejump will be granted. Minimum Exit Altitude: 10,500ft / 3200m, as measured by the approved competition PLD. If the PLD registers an exit lower than the minimum altitude, the competitor may choose to accept the score for the jump; otherwise a rejump will be granted automatically.",
    searchTerms: [
      "program",
      "rounds",
      "tasks",
      "nine flights",
      "exit altitude",
      "maximum exit altitude",
      "minimum exit altitude",
      "11000",
      "10500",
      "3353",
      "3200",
      "rejump",
      "invalid",
      "pld",
    ],
  },
  {
    id: "5.5-jump-run-exit-order",
    title: "5.5 Jump Run and Exit Order",
    text: "The jump run should be perpendicular to the wind line upwind of the designated landing area, established by the Meet Director. The number of competitors to exit on a single pass and the spacing of those exits will be determined by the Meet Director. The horizontal spacing must be no less than 600m and will be expressed to competitors as a time, in seconds, between exits. Immediately after exit, each competitor will turn directly towards his designated flight path.",
    searchTerms: [
      "jump run",
      "exit order",
      "exit spacing",
      "separation",
      "600m",
      "600",
      "wind line",
      "upwind",
      "meet director",
      "designated flight path",
      "turn after exit",
    ],
  },
  {
    id: "5.5.4-exit-separation-penalty",
    title: "5.5.4 Exit Separation Penalty",
    text: "Failure to comply with the required exit separation time will result in a review by the Meet Director and Chief Judge. If both determine that the deviation was not justified and resulted in a competitive advantage, a penalty will be applied: 50% result penalty for the first infringement; 100% result penalty for any subsequent infringements.",
    searchTerms: [
      "exit separation",
      "penalty",
      "penalties",
      "50%",
      "100%",
      "infringement",
      "competitive advantage",
      "not justified",
      "chief judge",
      "meet director",
    ],
  },
  {
    id: "5.6-flight-pattern-lane-penalties",
    title: "5.6 Flight Pattern and Lane Penalties",
    text: "A competitor must not leave his Designated Lane. Violation from the start of the Validation Window to the exit of the competition window affects the result as follows: less than 150m outside the Designated Lane, 10% reduction; 150-300m outside the Designated Lane, 20% reduction; more than 300m outside the Designated Lane, 50% reduction for the first infringement or a result of zero for any such infringement on a subsequent jump. The distance is measured at right angles to the Designated Lane boundary.",
    searchTerms: [
      "lane penalty",
      "designated lane",
      "outside lane",
      "leave lane",
      "10%",
      "20%",
      "50%",
      "zero",
      "150m",
      "300m",
      "infringement",
      "reduction",
      "boundary",
      "penalty",
      "penalties",
    ],
  },
  {
    id: "5.6.3-competitor-separation",
    title: "5.6.3 Competitor Separation",
    text: "At no time from the start of the Validation Window to deployment of the parachute shall a competitor come within 150m of any other competitor. Violation of this rule, as determined by the panel of judges, will lead to a result of zero for that jump.",
    searchTerms: [
      "separation",
      "competitor separation",
      "150m",
      "other competitor",
      "collision",
      "zero",
      "deployment",
      "validation window",
      "safety",
    ],
  },
  {
    id: "5.7-general-rules-deployment",
    title: "5.7 Deployment Altitude",
    text: "The deployment altitude for each competitor will be pre-determined by the Meet Director and must not exceed the lower boundary of the competition window, 1500m / 4921ft AGL. Any violation that results in endangering other competitors shall be considered a serious endangerment and referred to the Safety Panel.",
    searchTerms: [
      "deployment",
      "deployment altitude",
      "opening altitude",
      "1500m",
      "4921ft",
      "lower boundary",
      "safety panel",
      "serious endangerment",
      "meet director",
    ],
  },
  {
    id: "5.7.4-pld-accuracy-rejump",
    title: "5.7.4 PLD Accuracy and Rejump",
    text: "Within the validation window every PLD data sample must satisfy precision criteria. Every data sample must have a Spherical Error Probable value of less than 10 metres. If the accuracy requirement of the PLD data is not met then a rejump will be awarded.",
    searchTerms: [
      "pld",
      "accuracy",
      "precision",
      "sep",
      "spherical error probable",
      "10 metres",
      "data sample",
      "validation window",
      "rejump",
      "gps",
    ],
  },
  {
    id: "5.8-equipment-performance",
    title: "5.8 Performance Equipment",
    text: "All wingsuits must comply with Addendum D. Modifications relative to the wingsuit manufacturer’s design are not permitted, except those explicitly permitted in the competition rules. Modifications to improve fit to the competitor’s body are permitted. Modifications that alter the aerodynamic properties of the wingsuit are not permitted. Only marked suits may be used for the competition. Using an unmarked suit will lead to a result of zero for that jump.",
    searchTerms: [
      "wingsuit",
      "equipment",
      "modification",
      "modifications",
      "manufacturer",
      "aerodynamic",
      "aerodynamic properties",
      "marked suit",
      "unmarked suit",
      "addendum d",
      "zero",
      "inspection",
    ],
  },
  {
    id: "5.8.7-weight",
    title: "5.8.7 Additional or Removable Weight",
    text: "Competitors shall not carry additional or removable weight on their body or equipment. Competitors must be weighed at the start of the competition wearing all normal jump equipment to establish a baseline weight. Random weight checks may fluctuate from the baseline by no more than plus or minus 2kg before requiring inspection. If the addition or removal of weight is detected, the result for that jump will be zero. This decision is not grounds for protest.",
    searchTerms: [
      "weight",
      "additional weight",
      "removable weight",
      "baseline weight",
      "2kg",
      "random weight check",
      "zero",
      "protest",
      "equipment",
    ],
  },
  {
    id: "5.10-scoring",
    title: "5.10 Determination of Winners and Scoring",
    text: "Penalties from 5.6.2 and 5.6.3 are applied to the measured result for each task in each round. The penalized result is rounded to one decimal place for time and speed tasks, and whole numbers for the distance task. Each valid task is scored based on the top result of the task in that round. The top result scores 100%; other results are scored as a percentage of the top result. The three task scores for each competitor are added and rounded to one decimal place to give the total score.",
    searchTerms: [
      "scoring",
      "score",
      "winner",
      "winners",
      "penalty",
      "penalties",
      "rounding",
      "top result",
      "100%",
      "task score",
      "total score",
      "time",
      "distance",
      "speed",
      "ranking",
    ],
  },
  {
    id: "5.10.8-overall-champion",
    title: "5.10.8 Overall Champion",
    text: "Overall Champion: The competitor with the highest aggregate score from all valid tasks. If there is less than one valid round, there will be no Overall Champion.",
    searchTerms: [
      "overall champion",
      "champion",
      "aggregate score",
      "valid tasks",
      "valid round",
      "winner",
      "ranking",
    ],
  },
    {
    id: "addendum-c-performance-dfp-dl-penalties",
    title: "Addendum C — Performance Flying: DFP, DL, Penalties",
    text: "Addendum C relates to Performance Flying and covers the Designated Flight Path, Designated Lane, and penalties. It supports the performance lane and penalty rules, including how the Designated Flight Path and Designated Lane are applied for Performance Wingsuit Flying.",
    searchTerms: [
      "addendum c",
      "dfp",
      "designated flight path",
      "dl",
      "designated lane",
      "lane",
      "penalty",
      "penalties",
      "outside lane",
      "lane violation",
      "performance flying",
      "flight path",
      "flight line",
    ],
  },
  {
    id: "addendum-d-measuring-wingsuit",
    title: "Addendum D — Guidelines for Measuring a Wingsuit",
    text: "Arm span A is the maximum distance between the tips of the longest fingers on each hand with arms fully extended. The wingsuit is measured laid flat on the floor, all zippers fully closed, placed on top of a tape measure, and stretched lengthwise and spanwise with enough tension to remove slack but not stretch the fabric. The wingsuit span measurement B is conducted separately from any skydive parachute system, which must not be attached during the measurement process. The length C of any wingtip must not exceed the length D of the last rib of the arm wing fabric. Foot fairings or any other extension to the bottom of the sole of the bootie may extend perpendicular to the foot no more than 30 cm from the location that the foot makes contact with the inside of the bootie E. If winglets are present, the height F of a single winglet, measured perpendicular to the surface of the wingtip above the upper surface or below the lower surface of the wingtip, whichever is greater, will be doubled and added to the suit span measurement B. These measurements may be randomly checked throughout the competition at the discretion of the Chief Judge.",
    searchTerms: [
      "addendum d",
      "measure",
      "measuring",
      "measurement",
      "wingsuit measurement",
      "arm span",
      "span",
      "span measurement",
      "zippers",
      "laid flat",
      "tape measure",
      "parachute system",
      "rig attached",
      "wingtip",
      "wingtips",
      "wing tip",
      "wing tips",
      "last rib",
      "arm wing",
      "foot fairing",
      "foot fairings",
      "bootie",
      "booties",
      "30cm",
      "30 cm",
      "winglet",
      "winglets",
      "chief judge",
      "random check",
      "random checks",
    ],
  },
];