export type RuleSection = {
  id: string;
  title: string;
  text: string;
  searchTerms?: string[];
  imageSrc?: string;
  imageAlt?: string;
};

export const faiRuleSections: RuleSection[] = [
  {
    id: "source-2026",
    title: "Source: FAI Wingsuit Flying Competition Rules 2026",
    text: "Competition Rules Wingsuit Flying, 2026 Edition. Effective 01 March 2026. Ver. 2026.1, 2026-03-01. This search tool is for quick reference only. Competitors and officials should refer to the official FAI document for the authoritative rules.",
    searchTerms: [
      "source",
      "version",
      "2026",
      "official",
      "fai",
      "competition rules",
      "wingsuit flying",
      "wingtip",
      "wingtips",
      "wing tip",
      "wing tips",
    ],
  },

  {
    id: "2.1-general-definitions-wingtip-winglet",
    title: "2.1 General Definitions — Wingtip and Winglet",
    text: "Winglet: An additional vertical element mounted on the wingtip, oriented upward or downward. Wingtip: The outermost structural point or component of a wingsuit’s arm wing, usually rigid, that serves as a terminal boundary of the wing. It may include a handle or reinforced section designed for the pilot to hold or grip during flight to control the shape and tension of the wing.",
    searchTerms: [
      "wingtip",
      "wingtips",
      "wing tip",
      "wing tips",
      "winglet",
      "winglets",
      "arm wing",
      "wing handle",
      "handle",
      "grip",
      "rigid",
      "terminal boundary",
      "outermost structural point",
      "wingsuit arm wing",
    ],
  },

  {
    id: "2.2-competition-window",
    title: "2.2 Competition Window",
    text: "Competition Window: A vertical 1000-meter window, starting at 2500m / 8202ft Geometric Altitude and ending at 1500m / 4921ft Geometric Altitude, in which the performance of the wingsuit flyer is evaluated. The first crossing of the upper window boundary starts the evaluation process, which stops at the first crossing of the lower window boundary.",
    searchTerms: [
      "window",
      "competition window",
      "performance window",
      "scoring window",
      "2500",
      "1500",
      "2500m",
      "1500m",
      "8202",
      "4921",
      "altitude",
      "geometric altitude",
      "upper boundary",
      "lower boundary",
    ],
  },
  {
    id: "2.2-designated-lane",
    title: "2.2 Designated Flight Path and Designated Lane",
    text: "Designated Flight Path: The straight ground track between a point on the competitor’s flight path at the start of the Validation Window and a designated ground reference point. Designated Lane: A lane which is centred on the Designated Flight Path with a width of 600m.",
    searchTerms: [
      "lane",
      "designated lane",
      "flight path",
      "designated flight path",
      "600m",
      "600",
      "ground reference point",
      "reference point",
      "track",
      "line",
    ],
  },
  {
    id: "2.2-validation-window",
    title: "2.2 Validation Window",
    text: "Validation Window: The validation window is the part of the jump which is used to determine the accuracy of the PLD data. The validation window begins 9 seconds after the competitor’s vertical speed first reaches 10m/s and ends 66ft / 20m below the competition window.",
    searchTerms: [
      "validation",
      "validation window",
      "pld accuracy",
      "accuracy",
      "10m/s",
      "9 seconds",
      "20m",
      "66ft",
      "data",
      "gps",
      "position logging device",
    ],
  },
  {
    id: "3.1-pld",
    title: "3.1 Position Logging Device",
    text: "The PLD must record real-time three-dimensional position data with a resolution of at least 5Hz and a position accuracy SEP of less than 10 metres. The PLD must not require action by the competitor to function and must activate recording automatically. Tampering with the device, as determined by the Panel of Judges, will lead to a result of zero for the jump. This decision is not grounds for protest.",
    searchTerms: [
      "pld",
      "gps",
      "position logging device",
      "flysight",
      "logger",
      "data",
      "5hz",
      "accuracy",
      "sep",
      "10 metres",
      "tampering",
      "zero",
      "automatic recording",
      "device",
    ],
  },
  {
    id: "3.2-equipment-general",
    title: "3.2 Equipment — General Requirements",
    text: "All competitors must wear a wingsuit for all competition jumps. All equipment must be inspected by the judge panel to the satisfaction of the Chief Judge prior to use in the competition. Equipment that has not been inspected and approved by the judge panel may not be used on any competition jump. Violation of this rule shall result in a score of zero for the jump.",
    searchTerms: [
      "equipment",
      "inspection",
      "judge panel",
      "chief judge",
      "approved",
      "not inspected",
      "zero",
      "wingsuit",
      "competition jump",
    ],
  },
  {
    id: "3.2-electronics-altitude-warning",
    title: "3.2 Electronics and Audio Altitude Warning Device",
    text: "A competitor shall not wear any other electronic device or wires closer than 2.54cm from the official PLD as measured by the judging staff, except that a second identical PLD unit may be worn without regard to this separation requirement. Each competitor must wear a functioning audio altitude warning device on every jump. Failure to do so will lead to a result of zero for that jump.",
    searchTerms: [
      "electronics",
      "wires",
      "2.54cm",
      "pld",
      "second pld",
      "altitude warning",
      "audible",
      "audio altitude warning",
      "zero",
      "device",
    ],
  },
  {
    id: "5.2-objective",
    title: "5.2 Performance Event Objective",
    text: "The objective is to fly a single wingsuit in three separate tasks to demonstrate a combination of best lift, time task; best glide, distance task; and least drag, speed task. Each round of the event is comprised of the three tasks. Each task is performed on a separate flight.",
    searchTerms: [
      "objective",
      "performance",
      "time",
      "distance",
      "speed",
      "best lift",
      "best glide",
      "least drag",
      "task",
      "round",
    ],
  },
  {
    id: "5.3-tasks",
    title: "5.3 Performance Tasks",
    text: "Time Task: fly with the slowest fall rate possible through the competition window. The result is the time spent in the competition window, expressed in seconds. Distance Task: fly as far as possible through the competition window. The result is the straight-line distance flown over the ground while in the competition window, expressed in metres. Speed Task: fly as fast as possible horizontally over the ground through the competition window. The result is the straight-line distance flown over the ground while in the competition window divided by the time spent in the competition window, expressed in kilometres per hour.",
    searchTerms: [
      "time task",
      "distance task",
      "speed task",
      "slowest fall rate",
      "fall rate",
      "distance",
      "speed",
      "seconds",
      "metres",
      "kilometres per hour",
      "kph",
      "glide",
      "lift",
      "drag",
    ],
  },
  {
    id: "5.4-program-exit-altitude",
    title: "5.4 Program and Exit Altitude",
    text: "A competition shall consist of three rounds, with three tasks in each round, for a total of nine flights. Maximum Exit Altitude: 11,000ft / 3353m, as measured by the approved competition PLD. If the PLD registers an exit higher than the maximum exit altitude, the jump will be considered invalid and a rejump will be granted. Minimum Exit Altitude: 10,500ft / 3200m, as measured by the approved competition PLD. If the PLD registers an exit lower than the minimum altitude, the competitor may choose to accept the score for the jump; otherwise a rejump will be granted automatically.",
    searchTerms: [
      "program",
      "rounds",
      "tasks",
      "nine flights",
      "exit altitude",
      "maximum exit altitude",
      "minimum exit altitude",
      "11000",
      "10500",
      "3353",
      "3200",
      "rejump",
      "invalid",
      "pld",
    ],
  },
  {
    id: "5.5-jump-run-exit-order",
    title: "5.5 Jump Run and Exit Order",
    text: "The jump run should be perpendicular to the wind line upwind of the designated landing area, established by the Meet Director. The number of competitors to exit on a single pass and the spacing of those exits will be determined by the Meet Director. The horizontal spacing must be no less than 600m and will be expressed to competitors as a time, in seconds, between exits. Immediately after exit, each competitor will turn directly towards his designated flight path.",
    searchTerms: [
      "jump run",
      "exit order",
      "exit spacing",
      "separation",
      "600m",
      "600",
      "wind line",
      "upwind",
      "meet director",
      "designated flight path",
      "turn after exit",
    ],
  },
  {
    id: "5.5.4-exit-separation-penalty",
    title: "5.5.4 Exit Separation Penalty",
    text: "Failure to comply with the required exit separation time will result in a review by the Meet Director and Chief Judge. If both determine that the deviation was not justified and resulted in a competitive advantage, a penalty will be applied: 50% result penalty for the first infringement; 100% result penalty for any subsequent infringements.",
    searchTerms: [
      "exit separation",
      "penalty",
      "penalties",
      "50%",
      "100%",
      "infringement",
      "competitive advantage",
      "not justified",
      "chief judge",
      "meet director",
    ],
  },
  {
    id: "5.6-flight-pattern-lane-penalties",
    title: "5.6 Flight Pattern and Lane Penalties",
    text: "A competitor must not leave his Designated Lane. Violation from the start of the Validation Window to the exit of the competition window affects the result as follows: less than 150m outside the Designated Lane, 10% reduction; 150-300m outside the Designated Lane, 20% reduction; more than 300m outside the Designated Lane, 50% reduction for the first infringement or a result of zero for any such infringement on a subsequent jump. The distance is measured at right angles to the Designated Lane boundary.",
    searchTerms: [
      "lane penalty",
      "designated lane",
      "outside lane",
      "leave lane",
      "10%",
      "20%",
      "50%",
      "zero",
      "150m",
      "300m",
      "infringement",
      "reduction",
      "boundary",
      "penalty",
      "penalties",
    ],
  },
  {
    id: "5.6.3-competitor-separation",
    title: "5.6.3 Competitor Separation",
    text: "At no time from the start of the Validation Window to deployment of the parachute shall a competitor come within 150m of any other competitor. Violation of this rule, as determined by the panel of judges, will lead to a result of zero for that jump.",
    searchTerms: [
      "separation",
      "competitor separation",
      "150m",
      "other competitor",
      "collision",
      "zero",
      "deployment",
      "validation window",
      "safety",
    ],
  },
  {
    id: "5.7-general-rules-deployment",
    title: "5.7 Deployment Altitude",
    text: "The deployment altitude for each competitor will be pre-determined by the Meet Director and must not exceed the lower boundary of the competition window, 1500m / 4921ft AGL. Any violation that results in endangering other competitors shall be considered a serious endangerment and referred to the Safety Panel.",
    searchTerms: [
      "deployment",
      "deployment altitude",
      "opening altitude",
      "1500m",
      "4921ft",
      "lower boundary",
      "safety panel",
      "serious endangerment",
      "meet director",
    ],
  },
  {
    id: "5.7.4-pld-accuracy-rejump",
    title: "5.7.4 PLD Accuracy and Rejump",
    text: "Within the validation window every PLD data sample must satisfy precision criteria. Every data sample must have a Spherical Error Probable value of less than 10 metres. If the accuracy requirement of the PLD data is not met then a rejump will be awarded.",
    searchTerms: [
      "pld",
      "accuracy",
      "precision",
      "sep",
      "spherical error probable",
      "10 metres",
      "data sample",
      "validation window",
      "rejump",
      "gps",
    ],
  },
  {
    id: "5.8-equipment-performance",
    title: "5.8 Performance Equipment",
    text: "All wingsuits must comply with Addendum D. Modifications relative to the wingsuit manufacturer’s design are not permitted, except those explicitly permitted in the competition rules. Modifications to improve fit to the competitor’s body are permitted. Modifications that alter the aerodynamic properties of the wingsuit are not permitted. Only marked suits may be used for the competition. Using an unmarked suit will lead to a result of zero for that jump.",
    searchTerms: [
      "wingsuit",
      "equipment",
      "modification",
      "modifications",
      "manufacturer",
      "aerodynamic",
      "aerodynamic properties",
      "marked suit",
      "unmarked suit",
      "addendum d",
      "zero",
      "inspection",
    ],
  },
  {
    id: "5.8.7-weight",
    title: "5.8.7 Additional or Removable Weight",
    text: "Competitors shall not carry additional or removable weight on their body or equipment. Competitors must be weighed at the start of the competition wearing all normal jump equipment to establish a baseline weight. Random weight checks may fluctuate from the baseline by no more than plus or minus 2kg before requiring inspection. If the addition or removal of weight is detected, the result for that jump will be zero. This decision is not grounds for protest.",
    searchTerms: [
      "weight",
      "additional weight",
      "removable weight",
      "baseline weight",
      "2kg",
      "random weight check",
      "zero",
      "protest",
      "equipment",
    ],
  },
  {
    id: "5.10-scoring",
    title: "5.10 Determination of Winners and Scoring",
    text: "Penalties from 5.6.2 and 5.6.3 are applied to the measured result for each task in each round. The penalized result is rounded to one decimal place for time and speed tasks, and whole numbers for the distance task. Each valid task is scored based on the top result of the task in that round. The top result scores 100%; other results are scored as a percentage of the top result. The three task scores for each competitor are added and rounded to one decimal place to give the total score.",
    searchTerms: [
      "scoring",
      "score",
      "winner",
      "winners",
      "penalty",
      "penalties",
      "rounding",
      "top result",
      "100%",
      "task score",
      "total score",
      "time",
      "distance",
      "speed",
      "ranking",
    ],
  },
  {
    id: "5.10.8-overall-champion",
    title: "5.10.8 Overall Champion",
    text: "Overall Champion: The competitor with the highest aggregate score from all valid tasks. If there is less than one valid round, there will be no Overall Champion.",
    searchTerms: [
      "overall champion",
      "champion",
      "aggregate score",
      "valid tasks",
      "valid round",
      "winner",
      "ranking",
    ],
  },
    {
    id: "addendum-c-performance-dfp-dl-penalties",
    title: "Addendum C — Performance Flying: DFP, DL, Penalties",
    text: "Addendum C relates to Performance Flying and covers the Designated Flight Path, Designated Lane, and penalties. It supports the performance lane and penalty rules, including how the Designated Flight Path and Designated Lane are applied for Performance Wingsuit Flying.",
    imageSrc: "/rules/addendum-c-lanes-exiting.png",
    imageAlt: "FAI Addendum C diagram showing designated flight path, designated lane, and penalties.",
    searchTerms: [
      "addendum c",
      "dfp",
      "designated flight path",
      "dl",
      "designated lane",
      "lane",
      "penalty",
      "penalties",
      "outside lane",
      "lane violation",
      "performance flying",
      "flight path",
      "flight line",
    ],
  },
  {
    id: "addendum-d-measuring-wingsuit",
    title: "Addendum D — Guidelines for Measuring a Wingsuit",
    text: "Arm span A is the maximum distance between the tips of the longest fingers on each hand with arms fully extended. The wingsuit is measured laid flat on the floor, all zippers fully closed, placed on top of a tape measure, and stretched lengthwise and spanwise with enough tension to remove slack but not stretch the fabric. The wingsuit span measurement B is conducted separately from any skydive parachute system, which must not be attached during the measurement process. The length C of any wingtip must not exceed the length D of the last rib of the arm wing fabric. Foot fairings or any other extension to the bottom of the sole of the bootie may extend perpendicular to the foot no more than 30 cm from the location that the foot makes contact with the inside of the bootie E. If winglets are present, the height F of a single winglet, measured perpendicular to the surface of the wingtip above the upper surface or below the lower surface of the wingtip, whichever is greater, will be doubled and added to the suit span measurement B. These measurements may be randomly checked throughout the competition at the discretion of the Chief Judge.",
    imageSrc: "/rules/addendum-d-measuring-wingsuit.png",
    imageAlt: "FAI Addendum D diagram showing wingsuit measurement points.",  
    searchTerms: [
      "addendum d",
      "measure",
      "measuring",
      "measurement",
      "wingsuit measurement",
      "arm span",
      "span",
      "span measurement",
      "zippers",
      "laid flat",
      "tape measure",
      "parachute system",
      "rig attached",
      "wingtip",
      "wingtips",
      "wing tip",
      "wing tips",
      "last rib",
      "arm wing",
      "foot fairing",
      "foot fairings",
      "bootie",
      "booties",
      "30cm",
      "30 cm",
      "winglet",
      "winglets",
      "chief judge",
      "random check",
      "random checks",
    ],
  },

  {
  id: "sc5-5.3-protests",
  title: "SC5 5.3 Protests",
  text:
    "A protest must be made in writing, in English, and handed to the Meet Director together with the protest fee no later than two hours after official results for the event or round are posted, or after notification of a decision on a complaint. The protest may be presented by the Team Manager but must be signed by the competitor or Team Captain. Before a protest is submitted, the complaint procedure must first be followed. Each protest must identify the particular rule or rules involved. A protest cannot concern the evaluation of a jump or performance, or a score awarded by the Judges. A protest may be withdrawn before the Jury's final vote, and the fee is refunded if the protest is upheld.",
  searchTerms: [
    "protest",
    "protests",
    "complaint",
    "appeal",
    "jury",
    "meet director",
    "md",
    "team manager",
    "team captain",
    "two hours",
    "2 hours",
    "protest fee",
    "official results",
    "scoreboard",
    "judges",
    "score",
    "rule dispute",
    "written protest",
  ],
},

{
  id: "sc5-4.8-safety",
  title: "SC5 4.8 Competition Safety",
  text:
    "Any person, including a Judge, may report a safety matter during a competition to the FAI Controller. A Safety Panel is formed from the FAI Controller, the Meet Director and the Chief Judge for the discipline, with the FAI Controller acting as President. The Safety Panel investigates alleged safety violations and may issue a first, second or third level safety violation notice. A first level notice carries no penalty. A second level notice gives the competitor or team the maximum or minimum score, as appropriate, for the affected jump or performance. A third level notice disqualifies the competitor or team from the competition and, where they entered more than one event, from all those events. Penalties must be recorded and communicated in writing. Further violations escalate the notice level. These provisions are additional to discipline-specific safety and penalty rules. Safety Panel decisions cannot be protested or appealed to the Jury.",
  searchTerms: [
    "safety",
    "safety violation",
    "safety panel",
    "fai controller",
    "meet director",
    "chief judge",
    "judge",
    "first level safety notice",
    "second level safety notice",
    "third level safety notice",
    "warning",
    "maximum score",
    "minimum score",
    "disqualification",
    "written penalty",
    "appeal",
    "protest",
    "jury",
    "dangerous",
    "hazardous",
    "competition safety",
  ],
},

{
  id: "sc5-1.2-personal-requirements",
  title: "SC5 1.2 Personal Requirements",
  text:
    "Every competitor, record claimant and Team Manager must hold a valid FAI Sporting Licence. Every parachutist must wear one main and one reserve parachute attached to a single harness, and both parachutes must be certified as airworthy. At a First Category Event, both parachutes must be ram-air. Competitors must follow stricter national regulations where applicable. Suitable oxygen equipment must be provided for jumps above 4,500 metres above sea level. The minimum age for participation in a Skydiving First Category Event is 16 years.",
  searchTerms: [
    "personal requirements",
    "sporting licence",
    "FAI licence",
    "team manager",
    "main parachute",
    "reserve parachute",
    "two parachutes",
    "ram air",
    "airworthy",
    "national regulations",
    "oxygen",
    "4500 metres",
    "minimum age",
    "16 years",
    "eligibility",
  ],
},
{
  id: "sc5-1.3-general-safety",
  title: "SC5 1.3 General Safety Conditions",
  text:
    "Parachutists must practise safe parachuting and obey national and local regulations. For general skydiving, parachute deployment should be initiated by 600 metres above ground level, or at a higher altitude required by the relevant NAC. Unsafe parachuting is treated as a safety violation. A dangerous or hazardous safety violation may be treated as a Serious Infringement under the penalty rules. The maximum permitted ground wind speed is 11 metres per second unless the competition rules impose a lower limit. At FAI sanctioned events, the minimum jump altitude is 700 metres above ground for an individual and 900 metres for a team.",
  searchTerms: [
    "general safety",
    "safe parachuting",
    "deployment altitude",
    "600 metres",
    "600 m",
    "ground level",
    "AGL",
    "wind limit",
    "11 metres per second",
    "11 m/s",
    "minimum jump altitude",
    "700 metres",
    "900 metres",
    "individual jump",
    "team jump",
    "safety violation",
    "serious infringement",
    "national regulations",
    "local regulations",
  ],
},
{
  id: "sc5-4.5-competition-management",
  title: "SC5 4.5 Competition Management",
  text:
    "Competition management is responsible for operating the event in accordance with the Sporting Code, the applicable Competition Rules and official decisions. The Meet Director manages the competition programme and operational conduct of the event, works with the Chief Judge and other officials, communicates decisions and may take operational action necessary for safety, scheduling and the orderly completion of the competition.",
  searchTerms: [
    "competition management",
    "meet director",
    "MD",
    "competition programme",
    "event management",
    "official decision",
    "operational decision",
    "schedule",
    "competition officials",
    "chief judge",
    "FAI controller",
  ],
},
{
  id: "sc5-4.6-judges",
  title: "SC5 4.6 Judges",
  text:
    "FAI competition judging is carried out by appropriately rated FAI Skydiving Judges under the Chief Judge and Event Judges. Judges are assigned to the required judging panels and must display identification that does not refer to nationality. The organiser must provide sufficient technical and administrative support for the judging operation. Wingsuit Flying has its own FAI judging rating category.",
  searchTerms: [
    "judges",
    "FAI judge",
    "skydiving judge",
    "wingsuit judge",
    "WS judge",
    "chief judge",
    "CJ",
    "event judge",
    "EJ",
    "judging panel",
    "judge identification",
    "judge rating",
    "judging support",
  ],
},
{
  id: "sc5-4.7-jury",
  title: "SC5 4.7 Jury",
  text:
    "At a First Category Event, the Jury normally consists of a Jury President and two Jury members. Jury members must be independent of the competition operation and may not compete or hold an operational position at the event. The Jury considers protests and matters within its authority under the Sporting Code. For certain review panels, including Wingsuit Acrobatic video review, the Jury President may serve on a panel whose decision is not subject to appeal or protest.",
  searchTerms: [
    "jury",
    "jury president",
    "jury member",
    "three person jury",
    "protest hearing",
    "appeal",
    "independent jury",
    "operational official",
    "video review panel",
    "wingsuit acrobatic",
    "final decision",
  ],
},
{
  id: "sc5-4.9-conclusion-results",
  title: "SC5 4.9 Competition Conclusion and Results",
  text:
    "The competition is concluded after the required programme has been completed or officially terminated and the results have been approved. Official results are issued through the authorised competition process. Results, competition records, scoring information and required competition material must be completed and handled in accordance with the Sporting Code and the applicable Competition Rules.",
  searchTerms: [
    "competition conclusion",
    "official results",
    "final results",
    "results approval",
    "competition complete",
    "competition terminated",
    "scoreboard",
    "scoring information",
    "competition records",
    "result publication",
  ],
},
{
  id: "sc5-5.1-equipment-problems",
  title: "SC5 5.1 Equipment Problems",
  text:
    "Problems with equipment or apparel before a jump that prevent a competitor or team from jumping are handled under the failure-to-jump provisions. Equipment, apparel or freefall video equipment problems occurring during a jump are not normally grounds for a re-jump unless the specific Competition Rules provide otherwise. The competitor or team is scored using the available evidence.",
  searchTerms: [
    "equipment problem",
    "equipment failure",
    "apparel problem",
    "video equipment",
    "camera failure",
    "re-jump",
    "rejump",
    "available evidence",
    "failure to jump",
    "scoring evidence",
  ],
},
{
  id: "sc5-5.2-execution-of-jumps",
  title: "SC5 5.2 Execution of Jumps and Performances",
  text:
    "After the competition has been authorised to begin, competitors may not make non-competition skydives or use wind-tunnel time until their entered events are complete, unless exceptional permission is jointly given by the Chief Judge, Meet Director and FAI Controller. Jump order is prescribed by the Competition Rules, although the Meet Director may change it for re-jumps or important organisational reasons. Medical treatment alone is not a reason to change jump order. The Meet Director determines the order of events while taking weather, re-jumps and pending protests into account. Competitors must respond to official calls, be ready to jump and comply with the competition procedures. The chapter also governs failure to jump, interruptions, re-jumps, official scoring and posting of results. There is no general limit on the number of competition jumps or performances per day.",
  searchTerms: [
    "execution of jumps",
    "competition jump",
    "non competition jump",
    "wind tunnel time",
    "jump order",
    "order of events",
    "meet director",
    "chief judge",
    "FAI controller",
    "weather",
    "meteorological conditions",
    "call to jump",
    "ready to jump",
    "failure to jump",
    "interruption",
    "re-jump",
    "rejump",
    "official score",
    "official results",
    "jumps per day",
    "no limit",
  ],
},
{
  id: "sc5-5.4-penalties",
  title: "SC5 5.4 Penalties",
  text:
    "Except where another rule provides otherwise, the Meet Director may impose a penalty with the consent of the Jury. The Meet Director determines whether an infringement warrants a warning or a formal penalty. For Wingsuit Flying, a serious infringement may result in a deduction equal to 50 percent, rounded down, of the competitor's or team's highest score from any competition jump made up to the time of the infringement. Unsporting behaviour results in disqualification from further competition activity and removal from all unofficial and official standings and results.",
  searchTerms: [
    "penalty",
    "penalties",
    "warning",
    "infringement",
    "technical infringement",
    "serious infringement",
    "unsporting behaviour",
    "meet director",
    "jury consent",
    "50 percent",
    "50%",
    "score deduction",
    "highest score",
    "disqualification",
    "removed from results",
    "official standings",
    "cheating",
    "dangerous behaviour",
  ],
},
{
  id: "sc5-3.1-record-requirements",
  title: "SC5 3.1 General Record Requirements",
  text:
    "FAI skydiving record attempts must follow the applicable ISC Competition Rules. Competition records must be evaluated using the required judging equipment and scoring systems and certified by appropriately rated Judges. Wingsuit record performances must be judged by the number of Judges required by the Competition Rules, or by three qualified Judges where applicable. At least one required Judge must be physically present at the record location. Required recording media, photographs, results and claim documentation must be retained and submitted as prescribed.",
  searchTerms: [
    "record requirements",
    "record attempt",
    "world record",
    "competition record",
    "performance record",
    "wingsuit record",
    "record judges",
    "three judges",
    "judge present",
    "record certification",
    "record claim",
    "recording media",
    "photograph",
    "scoring system",
    "judging equipment",
  ],
},
{
  id: "sc5-3.2.10-wingsuit-competition-records",
  title: "SC5 3.2.10 Wingsuit Competition Records",
  text:
    "Wingsuit Performance competition records are recognised for the greatest horizontal distance achieved in a Distance Task round, the fastest speed achieved in a Speed Task round and the longest time achieved in a Time Task round. The Wingsuit Acrobatic longest-sequence record is the number of correctly completed grips in a compulsory round. Wingsuit competition records have General and Female categories.",
  searchTerms: [
    "wingsuit competition record",
    "WS record",
    "distance record",
    "greatest horizontal distance",
    "speed record",
    "fastest speed",
    "time record",
    "longest time",
    "distance task",
    "speed task",
    "time task",
    "acrobatic record",
    "longest sequence",
    "correct grips",
    "general category",
    "female category",
  ],
},
{
  id: "sc5-3.3.6-wingsuit-performance-records",
  title: "SC5 3.3.6 Wingsuit Performance Records",
  text:
    "For a Wingsuit Performance Record, every participant must wear a wingsuit that complies with the Sporting Code definition and no drogue may be used. Recognised records include Largest Formation No Grip in horizontal and vertical orientations, Large Formation Sequential No Grip, individual Time of Fall and individual Distance of Flight. Formation records require at least 16 persons. Time of Fall is measured in seconds to the nearest tenth. Distance of Flight is the straight-line distance measured in metres and rounded to the nearest whole metre. A new Time of Fall or Distance of Flight record must exceed the current record by at least 2 percent. These records must be measured using a suitable flight recorder or another reliable method with an overall error no greater than plus or minus 1 percent. The record file must include calibration, accuracy and data-integrity evidence.",
  searchTerms: [
    "wingsuit performance record",
    "WS performance record",
    "no drogue",
    "largest formation",
    "horizontal formation",
    "vertical formation",
    "sequential formation",
    "no grip",
    "minimum 16",
    "time of fall",
    "distance of flight",
    "straight line distance",
    "nearest tenth",
    "nearest metre",
    "2 percent",
    "2%",
    "flight recorder",
    "GPS record",
    "accuracy",
    "plus or minus 1 percent",
    "calibration",
    "data integrity",
    "tampering",
  ],
},
{
  id: "sc5-6-fai-skydiving-judges",
  title: "SC5 Chapter 6 FAI Skydiving Judges",
  text:
    "FAI Skydiving Judge ratings include a specific Wingsuit Flying rating. A valid Judge must have detailed knowledge of the Sporting Code General Section, Section 5, its annexes and the Competition Rules for the discipline being judged. Judges and Judges in Training must be able to understand and communicate in English. Judges must maintain a judging logbook containing their competition judging activity and required personal information. Chapter 6 also governs Judge training, rating categories, selection, duties and meetings.",
  searchTerms: [
    "FAI skydiving judge",
    "wingsuit judge rating",
    "WS judge",
    "judge requirements",
    "knowledge of rules",
    "English language",
    "judge logbook",
    "judge training",
    "judge selection",
    "judge duties",
    "judge meeting",
    "category 1 judge",
    "category 2 judge",
  ],
},

].map((section) => {
  if (!section.id.startsWith("sc5-")) {
    return section;
  }

  return {
    ...section,
    searchTerms: [
      ...new Set([
        ...section.searchTerms,
        "section 5",
        "sc5",
        "FAI section 5",
      ]),
    ],
  };
});

